-- CreateTable
CREATE TABLE "MESSAGE_STATS" (
    "ID" SERIAL NOT NULL,
    "USER_ID" INTEGER NOT NULL,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "MESSAGE_STATS_pkey" PRIMARY KEY ("ID")
);
